language: node_js
node_js:
  - "12"
branches:
only:
  - main
before_script:
  - echo 'Installing depedencies'
  - npm install
script:
- echo 'Running tests'
  - npm test
notifications:
  email:
  on_failure: lisalvarez398@gmail.com
  on_success: lisalvarez398@gmail.com